name: motion_cars
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  device_info_plus: ^12.2.0
  animated_toggle_switch: ^0.8.2
  provider: ^6.1.2
  loading_animation_widget: ^1.2.1
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/